### PR TITLE
propose 316

### PR DESCRIPTION
**Pull request by selfsame**

### CODE REVIEW

**Comment by william42** [comment]
I think you should clarify clause 2

**Comment by william42** [comment]
Wait crap

**Comment by bigjust** [comment]
lol @william42 violated VOWEL MINUS 2 POINTS

**Comment by datagrok** [comment]
_Time for debate_ states:

> If a rule-change as proposed ... is an amendment that makes no difference, or if it is otherwise of questionable value, then the other pla♆ers ma☢ suggest amendments or argue against the
proposal before the vote.

But this is not an amendment, and it doesn't sa☿ we _must_ argue,  so... carr☥ on 😄

Unfortunatel☮ this rule ma☮ be in violation of _All Created Rule Orders Now ⚒ield Monikers_:

> all newl⚜ proposed rules must carr☭ a title ... which is included ... as the first line of their contents.

If this passes, we'll have room for just two more rules before _Mutable rule limit_ throws a spanner in the works!

**Comment by selfsame** [comment]
@datagrok ᒩes it would violate A.C.R.O.N.:hammer_and_pick:.M. in its original form, I've updated the PR to include the title in the rule bod√

**Comment by piersb** [comment]
I'm guessing if we're not voting on this alreadx we will be soon. 

So 👍

**Comment by selfsame** [comment]
:+1:

**Comment by william42** [comment]
👍

**Comment by audiodude** [comment]
:-1: boooooo

**Comment by datagrok** [comment]
:+1:

**Comment by bigjust** [comment]
:-1:

**Comment by selfsame** [comment]
this passed so i'm closing it, someone's turn is up?

**Comment by datagrok** [comment]
The time is now Jul 15, 09:06AM.

selfsame opened PR #63, beginning their turn, at Jul 06, 05:55PM.
* Discussion is closed. Voting began at Jul 07, 05:55PM.
* Voting concluded and the PR was closed.

selfsame's turn ended Jul 12, 11:24AM.

  fonorobert forfeited their turn at  Jul 14, 11:24AM.
     @piersb must begin their turn between then and Jul 16, 11:24AM. (1d + 2h from now).
  @cardboard must begin their turn between then and Jul 18, 11:24AM. (3d + 2h from now).
  @william42 must begin their turn between then and Jul 20, 11:24AM. (5d + 2h from now).
    @kgrover must begin their turn between then and Jul 22, 11:24AM. (7d + 2h from now).
   @datagrok must begin their turn between then and Jul 24, 11:24AM. (9d + 2h from now).
    @bigjust must begin their turn between then and Jul 26, 11:24AM. (11d + 2h from now).
  @sashahart must begin their turn between then and Jul 28, 11:24AM. (13d + 2h from now).
  @audiodude must begin their turn between then and Jul 30, 11:24AM. (15d + 2h from now).
   @selfsame must begin their turn between then and Aug 01, 11:24AM. (17d + 2h from now).
 @fonorobert must begin their turn between then and Aug 03, 11:24AM. (19d + 2h from now).

**Comment by piersb** [comment]
Well, I'm not going to be able to put my full attention to it before my turn ends, so:

TIMER is fucking up rulemaking. Amendment to give us breathing space proposed. That should give me enough time (an extra day or two) to think about things.

Friendly amendments welcomed.

**Comment by piersb** [comment]
...crap, I'm on mobile and committed to master rather than making a pull request.

I'm running on fumes and have to go to bed. I won't be up before 11:whatever am.

Judge me tomorrow. If you want to invoke judgement.

**Pull request merged**
