### PR TITLE
Update audiodude's score after failed #6

### PR DESCRIPTION
**Pull request by audiodude**
We got into this problem with the last game that I played and quickly changed the rules, but by the current "letter of the law" there is no provision for who should update a player's score when it changes. We'll have to wing it for now.

#6 failed and so I have 0 - 10 = -10 points.

### CODE REVIEW

**Comment by fonorobert** [comment]
I say use the same logic as with new users: another player has to merge the PR

**Review by william42 — APPROVED** [review]
Looks good, in accordance with the rules.

**Comment by william42** [comment]
I thought the approval might work but I don't actually have write access...

**Comment by audiodude** [comment]
Added you with write access @william42, sorry about that!

**Pull request merged**
