### PR TITLE
Create 006-kgrover

### PR DESCRIPTION
**Pull request by kgrover**

### CODE REVIEW

**Comment by audiodude** [comment]
Welcome! You can start voting after the current round is finished (after @Cardboard has taken his turn).

**Comment by kgrover** [comment]
According to rule 105, 

> Every player is an eligible voter. Every eligible voter must participate in every vote on rule-changes.

This doesn't say _only_ players in the round. I'm new- maybe I'm missing a rule here?

**Comment by audiodude** [comment]
> The game shall consist of a series of rounds. Each round begins immediately after the end of the turn of the last player in the previous round. A player is said to be in a round if the player has a player file in the players/ directory when the round begins.

You didn't have a file in the players directory when the round began (it began as soon as there were five players, per https://github.com/audiodude/tiny-nomic/blob/master/mutable_rules/215_Begin-and-end-of-the-game.md)

But of course, this rule is subject to change! :smile:

**Comment by audiodude** [comment]
Hmm, you're right though, it says "a player is *in* a round" but never defines what that means regarding voting...

Welcome to the fun of Nomic...

**Comment by audiodude** [comment]
Okay so my message closing the voting was "15 minutes ago" according to Github and your comment about eligible voters was "13 minutes ago", so if you'd like to invoke judgement then I would be the judge (per https://github.com/audiodude/tiny-nomic/blob/master/mutable_rules/212_Judging.md)

**Comment by kgrover** [comment]
I won't invoke judgement at this point- I'll wait until the next round to vote!

**Pull request merged**
