### PR TITLE
Bribery

### PR DESCRIPTION
**Pull request by piersb**

### CODE REVIEW

**Comment by selfsame** [comment]
delightful, are you limited to one bribe per proposal?

**Comment by piersb** [comment]
The rule as written doesn't outlaw the proposer offering multiple bribes. I'm cool with that. :)

**Comment by selfsame** [comment]
:+1:

**Comment by piersb** [comment]
👍

**Comment by bigjust** [comment]
👍

**Comment by datagrok** [comment]
:+1:

**Comment by fonorobert** [comment]
love it 👍

**Comment by william42** [comment]
👍

**Comment by audiodude** [comment]
oh what the hell :+1:

**Comment by fonorobert** [comment]
Voting on this expired at 13:52 UTC today I think :)

**Comment by audiodude** [comment]
In general, we've been letting the rule proponent close the PR one way or another and start the next person's turn. Seems to be a bug in the TIMER rule, because now we're hung on @piersb doing so.

**Comment by piersb** [comment]
Well, I guess we all know what needs amending next then...

**Comment by audiodude** [comment]
@Cardboard you have 48 hours to take your turn!

**Comment by datagrok** [comment]
If we count the end of @piersb's turn as the moment @audiodude posted the above comment, then as of this post about 82.1 hours have elapsed, and we are 13.8 hours into @william42's turn (34.2 hours remaining to propose a rule)

If we imagine that TIMER paused until judgment #30 was closed, then as of this post about 78.3 hours have elapsed, and we are 17.7 hours into @william42's turn (30.2 hours remaining to propose a rule)

In both cases @Cardboard has forfeited their turn and lost 10 points :cry:

Unless my calculations are wrong? They follow:
```
>>> tz1 = datetime.datetime(2017,5,11,11,54) # datestamp of audiodude's comment
>>> tz2 = datetime.datetime(2017,5,11,15,54)
>>> (datetime.datetime.now() - tz1)
datetime.timedelta(3, 36741, 182960)
>>> (_.days * 24) + (_.seconds / 60 / 60)
82.20583333333333
>>> 48 - _
-34.20583333333333
>>> 48 + _
13.79416666666667
>>> (datetime.datetime.now() - tz2)
datetime.timedelta(3, 22505, 749084)
>>> (_.days * 24) + (_.seconds / 60 / 60)
78.25138888888888
>>> _ - 48
30.251388888888883
>>> 48 - _
17.748611111111117
```

**Comment by fonorobert** [comment]
your calculation seems correct @datagrok, it is now @william42's turn

**Pull request merged**
