### PR TITLE
(302) All Created Rule Orders Now Yield Monikers

### PR DESCRIPTION
**Pull request by selfsame**

### CODE REVIEW

**Comment by fonorobert** [comment]
I like the requirement for the title to form a word, I vote in favor :+1:

**Comment by audiodude** [comment]
Point of order: your file should end with a .md extension so that it renders properly in Github markdown.

**Comment by william42** [comment]
I like it as well! 👍

**Comment by Cardboard** [comment]
:+1:

**Comment by audiodude** [comment]
Looks Alright Mostly, Excited

:stuck_out_tongue: 

:+1:

**Comment by piersb** [comment]
Too badwrongfun NOT to vote for.

👍

**Comment by selfsame** [comment]
RESOLUTION PASSED

**Pull request merged**
