### PR TITLE
Transmute 117 to mutable

### PR DESCRIPTION
**Pull request by datagrok**
Sigh, I have a fun new rule that I'm eager to propose but I guess we'd better fix the rules first.

This proposal transmutes 117 to a mutable rule, so that it will no longer take precedence over FAST, as discussed in audiodude/tiny-nomic#31 and audiodude/tiny-nomic#32

However, the rules require that it receive a new number, and FAST refers explicitly to "Rule 117" so we may have more work to do before modifying it has the effect we want.

Since 117 is still in effect, its requirement that only one action be performed per turn outweighs mutable rule ACRONYM. (I'm not allowed to modify 117 while transmuting it to mutable.)

### CODE REVIEW

**Comment by william42** [comment]
I think "what should references to the old number of a renumbered law signify" is a good Judgement call.

**Comment by audiodude** [comment]
Also ACRONYM explicitly only applies to new rules, so it didn't come into play when 201 was amended (#26) either. Thanks for doing the dirty work, I would vote yes on this.

**Comment by audiodude** [comment]
> I think "what should references to the old number of a renumbered law signify" is a good Judgement call.

In my opinion, for maximum rules-lawyering (which is, of course, the fundamental point of the game), old numbers should not automatically "forward" to the newly numbered rule. That is, a clause that references a rule by number should refer specifically to that *exact* number. But, you know, that's just my opinion, man.

**Comment by william42** [comment]
That said, if 117 is renumbered to a value greater than 310, I believe it will no longer take precedence over FAST anyways.

**Comment by datagrok** [comment]
Mutable rule TIMER states

> (1.b) 24 hours for discussion and amendment of the proposed rule or amendment before votes are cast. This period is mandatory whether or not discussion occurs.  

Immutable rule 111 Time for debate, which takes precedence, states:

> If a rule-change as proposed is unclear, ambiguous, paradoxical, or destructive
> of play, or if it arguably consists of two or more rule-changes compounded or is
> an amendment that makes no difference, or if it is otherwise of questionable
> value, then the other players may suggest amendments or argue against the
> proposal before the vote. A reasonable time must be allowed for this debate. The
> proponent decides the final form in which the proposal is to be voted on and,
> unless the Judge has been asked to do so, also decides the time to end debate
> and vote.

Given that this rule is not unclear, nor ambiguous, nor paradoxical, nor destructive of play, nor does it consist of compounded changes, nor does it make no difference, nor is it of questionable value (as others have called for this very change),

and also given that I am the proponent of this change and 111 declares it to be my decision,

I hereby declare that discussion is over (or never should have happened) and voting begins now

:+1:

**Comment by piersb** [comment]
👍

**Comment by william42** [comment]
I'm going to vote :+1: but I'm slightly iffy on that use of the clause in 111 in cases other than this one: "Well, *I* think my rule is perfect, no debate!"

**Comment by audiodude** [comment]
That's a bold move, Cotton.

I think that TIMER can actually incrementally add a specific time window to the debate that is specified in 111, without precedence considerations coming into play. However, I also believe that 111 specifies the circumstances under which debate should occur and TIMER contradicts that by making the debate period mandatory. This is where precedence rules are relevant and for that purpose, all of TIMER is considered "null and void".

So I think this is fine and I vote 👍 

But anyone should feel free to invoke judgement on the matter.

**Comment by william42** [comment]
I think from a reading of the rules @audiodude is right and the circumstances in 111 override those in TIMER, but I think this could lead to some iffy situations in the future if people let it: someone could do a bad but improvable rule, and someone else could say it doesn't hit the requirements for debate to force it through and hurt the proposer's rule.  But there's a solution to this, and it's to transmute 111.

**Comment by william42** [comment]
That said, this passed last evening.

**Comment by audiodude** [comment]
Transmute all the things!

**Comment by audiodude** [comment]
Proposal passes with 4 voting yes, and 5 abstain.

Any player other than me can now merge the PR, per FAST.

@bigjust it would normally be your turn, but there is a pending judgement, so the rules state you cannot start your turn. Unfortunately, this puts us back in the situation where the TIMER is running but you cannot start your turn, so you may be forced to forfeit your turn if @kgrover doesn't respond to the judgement in time. In either case, there's no rule against getting your patch ready even before you submit the official pull request, so I would advise that in this situation.

**Comment by datagrok** [comment]
I would like to merge this PR but I have no write access to the repository.

Which is an egregious violation of rule 119 but I don't know in what way that affects the game.

Maybe it could be argued that since I have no commit access, I never really became an "active player," and all my actions so far have been illegal? 🙃

**Comment by audiodude** [comment]
Sorry about that, you've been added.

I don't think that you were not an "active player", because that is defined solely by having a file in the players/ directory, which you've had. The commit access is just an additional rule on top of that.

**Comment by william42** [comment]
@bigjust your turn is going to end in...about thirty minutes.

**Comment by audiodude** [comment]
Actually @bigjust isn't going to forfeit his turn I believe.

I think I read TIMER wrong:

> When a turn begins, 48 hours is allotted for the player whose turn it is to propose a rule or amendment.

So the 48 hours to not forfeit your turn only starts "When a turn begins". But since there is a pending judgement, the turn cannot begin until we have consent from a majority of players:

> When Judgment has been invoked, the next player may not begin his or her turn without the consent of a majority of the other players.

**Comment by audiodude** [comment]
Further, even though 310/FAST says that:

>In the case of a turn whose proposal is successful, the turn ends and the next turn subsequently begins when the relevant pull request adjusting the rules is merged and the game state contains the new rule.

Rule 212 on Judgement has precedence, and the turn cannot begin.

**Pull request merged**
