### PR TITLE
Amend Github Repository to allow related-rule tweaks

### PR DESCRIPTION
**Pull request by datagrok**
This amendment proposes that it's okay to change more than one rule file per pull request, if those changes are only to keep rules consistent with one another and the proposed rule-change.

Also tried to improve/clarify the language a bit.

### CODE REVIEW

**Comment by audiodude** [comment]
It still seems too vague to me what constitutes an 'administrative edit'. Too complicated.

:-1:

**Comment by piersb** [comment]
Too complicated. 👎

**Comment by sashahart** [comment]
I could approve of the spirit of this, and also with changes that leave gaps big enough to drive trucks through, but I'm objecting to this strictly because the diff is big and ugly.
:-1:

**Comment by datagrok** [comment]
> gaps big enough to drive trucks through

So harsh! 😭 I toned it down a bit, what do you think now?

**Comment by audiodude** [comment]
Wait, do we all have to revote now?

I still vote no: 👎

**Comment by datagrok** [comment]
Maybe I should amend the TIMER logic to be that only approval-votes have to be re-voted after a change.

**Comment by datagrok** [comment]
I think it's safe to assume our game has stalled out. Closing to remove these PRs from my list of open ones.

**Comment by audiodude** [comment]
Yes, I guess that's one way to finish a game of nomic....

Thanks to @bigjust @datagrok @piersb @sashahart @william42  @selfsame @kgrover @fonorobert @Cardboard for playing!

**Pull request closed without merging**
