### PR TITLE
Update william42's score

### PR DESCRIPTION
**Pull request by william42**
I believe, as per the rules, until 117 is transmuted to mutable so as to allow FAST to apply, this requires a majority vote.  And unfortunately, I don't think TIMER applies to these votes...

### CODE REVIEW

**Comment by audiodude** [comment]
The same thing happened in the last game of Nomic I ran on Github: https://github.com/audiodude/odeon/pull/11

:+1:

**Comment by audiodude** [comment]
BTW, we made 117 mutable and then amended it here: https://github.com/audiodude/odeon/pull/16/files

**Comment by william42** [comment]
:+1:

**Comment by datagrok** [comment]
:+1:

**Comment by fonorobert** [comment]
:+1:

**Comment by piersb** [comment]
This is my reading too. Meaning that all of the other scores are, I believe, invalid.

I INVOKE JUDGEMENT!

And I believe that @cardboard is the judge. 

Shall we leave the previous scores as-is, or reset them to zero?

Also: 👍

Also also: We really should get 117 transmuted and amended ASAP.

**Comment by datagrok** [comment]
With 5 positive votes out of 9 players, we can declare this update as successful.

I think the outcome of the judgement invoked by @piersb should not affect @william42's score (as it was correctly voted upon.) So we should be able to merge this now.

@piersb I think you might want to open a new github issue to contain the discussion for your Judgement, and record its resolution.

**Pull request merged**
