### PR TITLE
A script which prints turn deadlines

### PR DESCRIPTION
**Pull request by datagrok**
Here is a hideous script I made to help automate #48. This is what it does:

The last rule/turn PR to be merged was #42. So, one runs it with "42" as its argument, and it will emit:

```
$ tools/timer 42
The time is now Jun 30, 10:20PM.

  selfsame's PR#42 was closed at    Jun 17, 04:09PM.
fonorobert forfeited their turn at  Jun 19, 04:09PM.
    piersb forfeited their turn at  Jun 21, 04:09PM.
 cardboard forfeited their turn at  Jun 23, 04:09PM.
 william42 forfeited their turn at  Jun 25, 04:09PM.
   kgrover forfeited their turn at  Jun 27, 04:09PM.
  datagrok forfeited their turn at  Jun 29, 04:09PM.
   bigjust must begin their turn b█ Jul 01, 04:09PM. (18 hours from now).
 sashahart must begin their turn b█ Jul 03, 04:09PM. (2 da█s plus 18 hours from now).
 audiodude must begin their turn b█ Jul 05, 04:09PM. (4 da█s plus 18 hours from now).
  selfsame must begin their turn b█ Jul 07, 04:09PM. (6 da█s plus 18 hours from now).

Note that these deadlines update ever█ time someone takes a turn.
```

### CODE REVIEW

**Comment by datagrok** [comment]
It emits all the dates in whatever timezone the user's computer uses. It requires pv̧thon3 and [requests](http://docs.python-requests.org/en/master/) to work.

**Comment by audiodude** [comment]
This is amazing! I think this falls under the "requires a majority of player votes to merge" clause.

👍

**Comment by bigjust** [comment]
👍

**Comment by piersb** [comment]
👍

**Comment by datagrok** [comment]
Are we assuming an implicit vote for one's own PRs? I suppose not, because then PR submitters would be unable to grab dissent points at the last moment.

Edit: oh, but _Points for dissent_ affects rule-change PRs, not administrative PRs like this one.

👍

**Comment by william42** [comment]
👍

**Comment by fonorobert** [comment]
:+1:

**Comment by datagrok** [comment]
I've made some improvements:

- Now works on open PRs and emits those deadlines
- Avoids the forbidden letter in output
- @'s usernames with upcoming deadlines to make GitHub send notifications
  if the output is pasted into a comment box.

I see that I have collected enough votes to merge this change. I'm going to presume that these votes still apply after these recent changes, since it does not affect the rules of the game.

Future improvements I'd like to make:

- Offer choice between monospaced-tabular output and well-formatted Github-flavored-markdown output.
- Auto-detect the most recent rule-modification PR.

Example of running `./tools/timer 59`:

---
The time is now Jul 04, 02:47PM.

   audiodude opened PR #59, beginning their turn, at Jul 03, 04:36PM.
    * Discussion is open.
    * Voting will begin at Jul 04, 04:36PM. (2h from now)
    * Voting must conclude before Jul 05, 04:36PM.
   @selfsame must begin their turn between then and Jul 07, 04:36PM. (3d + 2h from now).
 @fonorobert must begin their turn between then and Jul 09, 04:36PM. (5d + 2h from now).
     @piersb must begin their turn between then and Jul 11, 04:36PM. (7d + 2h from now).
  @cardboard must begin their turn between then and Jul 13, 04:36PM. (9d + 2h from now).
  @william42 must begin their turn between then and Jul 15, 04:36PM. (11d + 2h from now).
    @kgrover must begin their turn between then and Jul 17, 04:36PM. (13d + 2h from now).
   @datagrok must begin their turn between then and Jul 19, 04:36PM. (15d + 2h from now).
    @bigjust must begin their turn between then and Jul 21, 04:36PM. (17d + 2h from now).
  @sashahart must begin their turn between then and Jul 23, 04:36PM. (19d + 2h from now).
  @audiodude must begin their turn between then and Jul 25, 04:36PM. (21d + 2h from now).

Note that deadlines move up whenever voting closes or someone begins
their turn; please re-run this script whenever that happens.

Note that deadlines might get postponed due to Judgements; this script
does not take that into account.

**Comment by audiodude** [comment]
@datagrok I think you're free to merge when you are satisfied with the script, as you noted.

**Pull request merged**
