### PR TITLE
(303) Vote On Creation As Logical

### PR DESCRIPTION
**Pull request by fonorobert**
This proposal serves to clarify the unclear situation around recently joined users voting in an ongoing round.

### CODE REVIEW

**Comment by audiodude** [comment]
Thank you, a hearty :+1:

**Comment by selfsame** [comment]
:+1:

**Comment by fonorobert** [comment]
Note that as per the recent judgment (https://github.com/audiodude/tiny-nomic/issues/13) a vote from all players is now required to pass this proposal, including @william42 and @kgrover

**Comment by william42** [comment]
As per judgement, my vote here is unambiguously valid; I use my valid vote to cement this validity with a 👍.

**Comment by piersb** [comment]
Ordinarily I'd be wary about cementing a judge's decision into statutory law instead of case law. However, https://github.com/audiodude/tiny-nomic/blob/master/mutable_rules/212_Judging.md states quite clearly that new judges need not consider case law.

So 👍

**Comment by kgrover** [comment]
I also approve; 👍

**Comment by william42** [comment]
I'm now required to vote, so I'll do so: I approve.  👍

**Comment by Cardboard** [comment]
great :+1:

**Comment by selfsame** [comment]
RESOLUTION PASSED, @fonorobert please handle your point reward, @piersb is next up!

**Comment by audiodude** [comment]
Just one thing, the rules state that the proponent of a rule change will decide when debate has ended and the vote should be taken. I would interpret this as the proponent should merge the rule, which is what makes it take effect and ends his or her turn.

**Comment by fonorobert** [comment]
As the required votes have been cast I agree that the proposal passed. As the PR is already merged this should clarify that my turn has indeed ended.

**Pull request merged**
