### PR TITLE
repeal 314 V.O.W.E.L.

### PR DESCRIPTION
**Pull request by bigjust**

### CODE REVIEW

**Comment by piersb** [comment]
👍

**Comment by audiodude** [comment]
goodb---- uh farewell  👍

**Comment by selfsame** [comment]
:-1: and pinging @fonorobert @Cardboard @william42 @kgrover @datagrok @sashahart

**Comment by datagrok** [comment]
```                                        
▄▄▄    ▄▄▄                        ▄▄    
 ██▄  ▄██                         ██    
  ██▄▄██    ▄█████▄  ▀██  ███     ██    
   ▀██▀     ▀ ▄▄▄██   ██▄ ██      ██    
    ██     ▄██▀▀▀██    ████▀      ▀▀    
    ██     ██▄▄▄███     ███       ▄▄    
    ▀▀      ▀▀▀▀ ▀▀     ██        ▀▀    
                      ███               
```
:+1:

**Comment by william42** [comment]
👍

**Comment by fonorobert** [comment]
👎 i like this state of constant dodging, we should outlaw more letters

**Comment by bigjust** [comment]
:+1:

**Comment by selfsame** [comment]
ceaser

**Comment by datagrok** [comment]
I think I should hedge my vote with a comment that if this rule were re-introduced I would vote in favor of that, too. 🙃

I'm starting to feel like any proposal that isn't abjectly invalid or game-breaking should get (my) approval. That would make the game feel like an offline game, where part of the strategy is that you sometimes have to cope with weird rules, decide between repealing the ones you don't like or proposing your own when it's your turn, get into ko-fights enacting and repealing the same contentious rule over and over...

**Comment by audiodude** [comment]
I count 5 for, 2 against, and this should have been merged as passing a while ago.

**Pull request merged**
