### PR TITLE
308 - Clarify turn order and rounds in 201

### PR DESCRIPTION
**Pull request by fonorobert**
The proposed modifications are the same as @audiodude proposed in #19

### CODE REVIEW

**Comment by datagrok** [comment]
What will happen to other rules which would refer to the non-existent concept of "round?" Like

mutable_rules/303_Vote-On-Creation-As-Logical.md
> (b) For the purposes of voting, a player being _in_ a round (as outlined in rule 201) shall be irrelevant.

mutable_rules/215_Begin-and-end-of-the-game.md
> The game shall begin (the first round shall start) once there are at least 5

mutable_rules/203_Rule-changes-unanimous-at-first.md
> voters. If this rule is not amended by the end of the second round, it

I would suggest that these be amended as part of this PR but rule 117 has language describing "exactly one" action per PR:

```
Pull Requests must perform exactly one of the following actions:
...
3. Modify an existing rule file, when an amendment is made
```

So from rule 211 it seems that the amended rule (201) will take precedence over rules 203, 215, and 303. The effect of which being only that rule changes will need to be unanimous until 303 is amended.

**Comment by audiodude** [comment]
You're completely correct about only being able to modify one rule. However, if you look at the rules for precedence (https://github.com/audiodude/tiny-nomic/blob/master/mutable_rules/211_Precedence.md) you'll see that rules are allowed to state that they take precedence over other rules that would, by default, take precedence over them. In fact, that's what's happening in your first example. This is the mechanism by which a single amendment or rule change can effectively modify rules throughout the rulebase.

Frankly, I don't think that this amendment "abolishes" rounds as much as de-emphasizes them. It still states:
> If there is no higher number, the next round begins with the player with the lowest number.

215 still allows for the first round to start, and then the second round would start according to the amended rule 308. This also allows for the second round to end, which allows for 203's fallback clause to kick into effect.

And back to the precedence rules:
> So from rule 211 it seems that the amended rule (201) will take precedence over rules 203, 215, and 303.

Actually, by 211 the *lower* number rule takes precedence, so you have it reversed.

**Comment by datagrok** [comment]
@audiodude wow, I overlooked the phrase in 211 `... or takes precedence over another rule (or type of rule),` as well as the fact that rule 201 will become rule 308. Thanks!

**Comment by audiodude** [comment]
Okay from what I can tell it has been 24 hours since the rule change was proposed. Voting has begun and I vote 👍

**Comment by datagrok** [comment]
:+1:

**Comment by william42** [comment]
👍

**Comment by bigjust** [comment]
👍

**Comment by kgrover** [comment]
👍

**Comment by selfsame** [comment]
:+1:

**Comment by fonorobert** [comment]
Umm, I think I'm supposed to vote, too? In any case, :+1:

**Comment by fonorobert** [comment]
Voting ends today at 11:24 UTC as per 307, @Cardboard @piersb vote now or forever hold your peace (well, till next time someone proposes to amend this at least)

**Comment by fonorobert** [comment]
Voting is completed, 2 abstain, 7 vote yes, the proposal passes.

**Comment by audiodude** [comment]
Sorry, but I believe the proposal fails. It's still the case that voting has to be unanimous.

https://github.com/audiodude/tiny-nomic/blob/master/mutable_rules/203_Rule-changes-unanimous-at-first.md
> if and only if the vote is unanimous among the eligible voters.

It very clearly doesn't read "among the voters who voted/participated actively".

If you disagree, we should invoke judgement.

**Comment by audiodude** [comment]
Okay I invoked judgement partly because I wanted to stop the timer on the 24 hours for the next turn to start while we figure this out.

**Comment by selfsame** [comment]
#28 has been resolved, this proposal has passed and @piersb is up next

**Pull request merged**
