### PR TITLE
Peace and Joy to the World!

### PR DESCRIPTION
**Pull request by piersb**

### CODE REVIEW

**Comment by fonorobert** [comment]
Let's spread some Christmas joy! 👍

**Comment by Cardboard** [comment]
Do games actually last _that_ long? If not, then enjoy the free points (because nobody will ever benefit from this rule), but I'll vote :+1: in hopes of the game continuing until Christmas!

**Comment by kgrover** [comment]
No objections here, 👍

**Comment by audiodude** [comment]
Did you mean 11:59PM? Or is it only for the morning of Christmas? I'm not sure what the rules are regarding changing an already submitted proposal. It might fall under https://github.com/audiodude/tiny-nomic/blob/master/immutable_rules/116_Not-otherwise-prohibited.md and be allowed, but it would be awkward in the case of existing votes.

As far as the game lasting until Christmas, remember that, per https://github.com/audiodude/tiny-nomic/blob/master/mutable_rules/215_Begin-and-end-of-the-game.md 

> The game does not necessarily end when it is won

**Comment by william42** [comment]
I suspect we should have a call for judgment on amending proposals.

**Comment by fonorobert** [comment]
From https://github.com/audiodude/tiny-nomic/blob/master/immutable_rules/111_Time-for-debate.md it seems modifications of a submitted proposal must happen before voting starts:
> other players may suggest amendments or argue against the proposal before the vote

Based on this I don't think judgment is needed, modification is not possible after the first vote is cast.

Also based on rule 111 the proponent of the proposal is free to say "no voting yet" and wait a while in case other players want to debate the proposal.

**Comment by audiodude** [comment]
That's an excellent reading of the rules @fonorobert and I agree completely.

Based on the typo, I'm going to vote no :-1:

**Comment by selfsame** [comment]
well we haven't exactly been observing 111's "A reasonable time must be allowed for this debate"

(:+1: for CHRISTMAS)

**Comment by fonorobert** [comment]
@selfsame my reading of 111 is that it's all in the context of the proponent being the one determining when voting starts. No proponent yet said when voting should start so I think it's just that we haven't noticed this so far :smile:

**Comment by piersb** [comment]
I actually meant 11:59PM. 

But we must judge the rule on what's written in the pull request (unless there's a currently-existing rule I'm not aware of for alterations) rather than what may or may not have been in my head, so the proposal is morning GMT.

**Comment by piersb** [comment]
Also: audiodude? When we still require unanimity? And you're stopping Christmas Points in the morning purely because the original rule-writer made a typo?

Think of all the poor shivering orphans, Grinch!

**Comment by piersb** [comment]
Also-also: How do I get to quote someone else? Is it just a > and a copy-and-paste?

**Comment by selfsame** [comment]
>When we still require unanimity?

Actually per https://github.com/audiodude/tiny-nomic/blob/master/mutable_rules/203_Rule-changes-unanimous-at-first.md I would think it goes like:
1. proposal debated
2. proposal voted on 
3. if unanimous proposal passes
4. if not unanimous proposal can be amended (GOTO 1)
5. if majority of votes are yes proposal passes

**Comment by audiodude** [comment]
@selfsame that is not the case. Rule 203 states:

> If this rule is not amended

Not "if *the* rule is not amended". It is referring to itself, such that unanimous votes are only required in the first two rounds. Per https://github.com/audiodude/tiny-nomic/blob/master/immutable_rules/104_All-rule-changes-voted-on.md the rule is only adopted if it receives the required number of votes, there is no revoting provided for.

Speaking of rounds, we're going to come up against an awkward situation soon in that players 005 and 006 are still not technically *in* the round per https://github.com/audiodude/tiny-nomic/blob/21429fde4eb8455e72743e2946d37aa889677082/mutable_rules/201_Turn-alternation.md and also per that rule:

> Each round begins immediately after the end of the turn of the last player in the previous round.

My read of this is that @william42 and @kgrover were not "in" this round, per the rules, so play proceeds to  the next round and my turn next.

Edit: Sorry, obviously @Cardboard has to take his turn, THEN it will be passing back to me.

**Comment by audiodude** [comment]
I just want to say I'm sorry, I wrote rule 201 and I didn't realize what a pain it would be.

**Comment by piersb** [comment]
If only there were some way to amend it.

IF ONLY.

**Comment by william42** [comment]
:+1: for Christmas cheer.

**Comment by audiodude** [comment]
It looks like this has all voters voting, so @piersb you can close it and end your turn at your discretion.

**Comment by piersb** [comment]
ta for the heads up

**Comment by piersb** [comment]
But I make it as non-una

**Comment by audiodude** [comment]
@Cardboard it is your turn, just a friendly ping in case you didn't realize it.

**Pull request closed without merging**
