### PR TITLE
Proposal: ROULETTE

### PR DESCRIPTION
**Pull request by datagrok**

### CODE REVIEW

**Comment by audiodude** [comment]
1/16 chance? Too rich for my blood. Maybe '00' and I would be swayed.

But again, I love the creativity!

👎

**Comment by piersb** [comment]
Too random. I like gameplay events to be under my control - even if there's a random chance, it should be my choice to trigger the random event in the first place.

👎

**Comment by sashahart** [comment]
Too much updating of score files
:-1:

**Comment by datagrok** [comment]
@audiodude @piersb would you perhaps be swayed If the random chance were still one in sixteen, but the rule was only triggered if the player merging the rule writes "ROULETTE" in the merge comment? (The comment box that appears when one clicks "Merge pull request")

**Comment by piersb** [comment]
I'd be swayed if the ROULETTE only affected the person merging and deciding to gamble; not really interested in having my score randomly become someone elses.

I also hate Fluxx.

**Pull request closed without merging**
