### PR TITLE
P.A.T.C.H. - Proposing A Thing Can Help 

### PR DESCRIPTION
**Pull request by Cardboard**

### CODE REVIEW

**Comment by audiodude** [comment]
I like the spirit of this, but I think per discussion on #15, the rule https://github.com/audiodude/tiny-nomic/blob/master/immutable_rules/111_Time-for-debate.md provides for discussion, debate, and amendments of rule proposals "before the vote".

So, consider this comment the start of debate. I don't agree with the language in this PR that "the creator of the proposal may include the amendment in their proposal". So even if all other players vote YES for an amendment, the rule proponent can still exclude it?

I also like that the prior rule allows for multiple amendments and doesn't require them to be voted on. It is up to the rule proponent to include them in a way that makes their rule most favorable to the other players.

I'm leaning no on this, but I want to refrain from voting to allow:

> The proponent decides the final form in which the proposal is to be voted on and, unless the Judge has been asked to do so, also decides the time to end debate and vote.

**Comment by audiodude** [comment]
In fact, if you read https://github.com/audiodude/tiny-nomic/blob/master/immutable_rules/110_Immutable-rules-take-precedence.md the right way, the fact that 111 allows for multiple amendments would seem to conflict with 305 and thus render 305 "entirely void".

**Comment by audiodude** [comment]
Also, by https://github.com/audiodude/tiny-nomic/blob/master/mutable_rules/211_Precedence.md, if you suspect that 111 conflicts with https://github.com/audiodude/tiny-nomic/blob/master/immutable_rules/117_Github-repository.md

> Players vote on Pull Requests/proposals by putting either "+1" or "-1" as a comment on the Pull Request, or by using the proper :+1: or :-1: emoji on the Pull Request comment.

Then 111 would take precedence and the proponent of a rule change should really be deciding how voting is done, not the +1/-1 method.

Okay I'll shut up now.

**Comment by fonorobert** [comment]
@audiodude re. your last comment, I think you might be misunderstanding 111, my reading is that 

>The proponent decides the final form in which the proposal is to be voted on

means the proponent decides the final form of the proposal, not the form of voting.

**Comment by audiodude** [comment]
@fonorobert Oh! That makes a ton more sense and is much more consistent with the way we've been playing anyways, thanks!

**Comment by fonorobert** [comment]
As to the current proposal, I like the idea of formalizing how a proposal gets amended, including the requirement to vote on amendments separately. I agree however that it'd be better to have the proponent be required to include the amendment in the proposal.

**Comment by Cardboard** [comment]
>  I agree however that it'd be better to have the proponent be required to include the amendment in the proposal.

I now agree with this. My initial thoughts were that the amendment could possibly cause the proposal to stray in an unwanted direction, so letting the proponent decide whether to include them or not would give them the power to maintain their original proposal's integrity. But then it kind of makes voting on the amendment less powerful if the proponent can simply say "no" after a successful vote and merge the original. _Requiring_ an "passed" amendment to be included in the proposal makes the most sense I think.

**Comment by william42** [comment]
Honestly, as written, I can see this allowing another user to effectively hijack a user's turn if there's no mechanism to reject the amendment and allow the original proposal to be voted on.  My intuition is towards the proposer having to accept to allow the amendment be voted on at all.

**Comment by fonorobert** [comment]
@william42 that's a good point, I like the idea of having the proponent of the original proposal put the amendment up for vote. Once the amendment is voted on however I still think the proponent should be required to update the original proposal with it.

**Comment by Cardboard** [comment]
Agreed. So I guess what we have now is (correct me if I'm wrong):  
- Anyone can propose an amendment (which is in original ruleset)  

- The proponent may choose to have an amendment voted on (and if it passes, the whole thing passes, not only part of it — i.e. the original proposal or amendment cannot be passed without the other _once the proponent chooses to hold a vote on an amendment_)  

- If the vote on the amendment fails, so does the vote on the proposal by extension

- Previous voting / suggestion rules apply — amendments must be suggested before any voting occurs, and a majority vote is required (after round 2)

**Comment by audiodude** [comment]
The original proposal also is not clear about whether the proponent of a rule will vote on amendments, though it would seem to imply that yes this is the case.

Edit: sorry, I see the last sentence now: each "user" (though I would prefer the term player here) can vote on proposals and amendments.

**Comment by audiodude** [comment]
> the original proposal or amendment cannot be passed without the other
> If the vote on the amendment fails, so does the vote on the proposal by extension

I don't think this is true either from the current proposal or what has been discussed.

**Comment by Cardboard** [comment]
My bad. I think it would make sense though to either reject or accept the whole thing though, as otherwise the proponent could have multiple chances of getting _some_ amended variation of their proposal passed. This would limit each player's turn to a single round of voting, which seems preferable to me.  
  
And choosing to have a vote on an amendment implies a YES vote I guess, but maybe the proponent shouldn't get a vote?

**Comment by audiodude** [comment]
I think it is perfectly valid to vote YES on an amendment to a proposal that you don't want to pass. Simply put "I don't agree with X, but X+Y is less bad so I vote yes on the amendment in case the full proposal passes".

**Comment by piersb** [comment]
Sounds confusing to me, and also (per upstream discussion of 111) un-necessary.

https://github.com/audiodude/tiny-nomic/blob/master/immutable_rules/111_Time-for-debate.md

Per 111, we can discuss away with as many suggested alterations as we like until such time as proponent says "discussion's over, here's the final wording, time to vote!"

So I'm minded to vote no when voting begins, as it seems to me that a more generic and useful feature than PATCH already exists in rule 111.

**Comment by Cardboard** [comment]
I guess voting should begin (based on the bullet points above, + audiodude's susbsequent X/X+Y suggestion), so that we can move on to greener pastures.

**Comment by audiodude** [comment]
If you'd like to make changes to the proposal before voting begins, @Cardboard, you can commit to the existing branch and push your changes, the PR will update automatically.

**Comment by audiodude** [comment]
Okay I'll open the voting.

I like that the prior rules allow for freeform/multiple amendments and don't require voting (which I feel will slow things down).

I vote no 👎 

Edit: I see that the current version of the proposal allows for "amendments". I still don't like the voting so my vote stays the same.

**Comment by selfsame** [comment]
:-1: (think the amending process needs some formalization, but not dedicated votes per amendment)

**Comment by Cardboard** [comment]
Can I close this or must I wait for everyone to vote? I'm writing a paper currently, but I'll check the rules myself later if nobody knows off the top of their head.

**Comment by fonorobert** [comment]
I vote 👎. @Cardboard as far as I understand everyone has to cast a vote.

**Comment by piersb** [comment]
Yup, per https://github.com/audiodude/tiny-nomic/blob/master/immutable_rules/105_Eligible-voters.md you can't close it until we've all voted.

Which means if one of us dies suddenly, the round can never end.

👎

**Comment by fonorobert** [comment]
That's dark 😱 Also accurate 😄

**Comment by audiodude** [comment]
> can't close it until we've all voted.

Yes, that's the proper reading. A good rule that I would vote for would be some kind of "if a player hasn't voted within 48 hours of the start of voting, it counts as a NO vote" (we're allowed to collude on rules because this is a computer game, per https://github.com/audiodude/tiny-nomic/blob/master/mutable_rules/210_Conspiracy-to-rule-change.md)

**Comment by william42** [comment]
Heh, I was actually planning on proposing a rule that counted a lack of vote after 48 hours as deliberate abstention (as well as skipping turns for inactivity). Anyways, as my earlier objections hold and there might already be a practice in place, 👎.

Edit(@audiodude): Clean up response a bit.

**Comment by audiodude** [comment]
Paging @kgrover, your vote is required!

**Comment by kgrover** [comment]
Sorry for the delay- as with other votes I'll vote 👎

**Comment by audiodude** [comment]
@Cardboard feel free to close this PR and update your score. The next round will then begin with my turn (see https://github.com/audiodude/tiny-nomic/pull/15#issuecomment-294016099).

**Pull request closed without merging**
