### PR TITLE
Amend ACRONYM to allow acronyms in filenames

### PR DESCRIPTION
**Pull request by datagrok**
Allows filenames to be their acronyms, not their full titles.

Also, performs that change for all rules implemented under ACRONYM.

### CODE REVIEW

**Comment by audiodude** [comment]
I like the rule amendment, but don't like changing all the existing files.

:+1:

I suppose changing the existing files won't be allowed anyways if #72 doesn't pass anyways

**Comment by piersb** [comment]
Ditto @audiodude on both points.

👍

**Comment by sashahart** [comment]
This is stupid, but it has style
:+1:

**Comment by datagrok** [comment]
Rebased to lose the commit that renames all the existing files. Also 👍

**Pull request closed without merging**
