### PR TITLE
update fonorobert score after successful 308

### PR DESCRIPTION
**Pull request by fonorobert**

### CODE REVIEW

**Comment by selfsame** [comment]
I believe you should award yourself 17 points, as the fraction of favorable votes is 1.0 :)

**Comment by fonorobert** [comment]
Good point, thanks, updated!

**Comment by audiodude** [comment]
Shouldn't the points be some fraction of 17, because (https://github.com/audiodude/tiny-nomic/blob/master/mutable_rules/202_Parts-of-a-turn.md):

>and multiply the result by the fraction of favorable votes it received

Or do the abstain votes count as favorable votes now too....  😛

**Comment by william42** [comment]
The abstentions don't count as votes, per #28.

**Comment by audiodude** [comment]
https://github.com/audiodude/tiny-nomic/blob/master/mutable_rules/307_Temporal-Initiated-Motion-Every-Rule.md

> are considered as having voted to "abstain"

**Comment by audiodude** [comment]
Though seeing as if we invoked judgement again, @selfsame would be the judge again and we already know his position on this matter....sigh.

I hope you're all satisfied with your life choices.

**Comment by fonorobert** [comment]
I agree, abstentions need clarification as soon as possible. I'm pretty happy with the judgment though 😛

**Pull request merged**
