### PR TITLE
313: Amend 311 to allow for changing a player's score, among other things

### PR DESCRIPTION
**Pull request by audiodude**
The important thing to note is that the new sixth item and the eighth item allow for additional rules to modify what is and isn't a valid pull request, without having to further modify this specific rule.

### CODE REVIEW

**Comment by audiodude** [comment]
Note that we are past the second round now, so the rule proposal only needs a majority of yes votes to pass.

**Comment by piersb** [comment]
I mostly like this - but the removal of the ability to vote with a thumbs-up or thumbs-down emoji is going to be a dealbreaker for me unless there's some aspect of bribery in play.

**Comment by audiodude** [comment]
The part of the sentence that was removed:

> or by using the proper :thumbsup: or :thumbsdown: emoji on the Pull Request comment.

Refers to attaching an emoji directly to the comment that announces the pull request. No one has ever done that, so it has been removed.

In fact, all of the votes to this point have been invalid because people have used 👍  and 👎  emojis in follow up comments, instead of literal "+1" and "-1" as the rule prescribes.

I agree it needs a bit more work though.

**Comment by audiodude** [comment]
The original rule was talking about what i did to your comment, attach an emoji to it. I've clarified the rule further, what do you think?

**Comment by piersb** [comment]
Reading "a comment on the Pull Request" as being a different thing to "the Pull Request comment" would be a very odd way of reading the rule.

**Comment by piersb** [comment]
But that clarification is good for me. Ready to vote.

**Comment by audiodude** [comment]
"The pull request comment" was intended to refer to specifically the comment that introduces the Pull Request. Notice the definite article. It's one specific thing, while Pull Requests can have multiple comments in general "on" them.

But nobody knew what it meant or used it properly so I got rid of it.

**Comment by sashahart** [comment]
> In fact, all of the votes to this point have been invalid because people have used :+1: and :-1: emojis in follow up comments, instead of literal "+1" and "-1" as the rule prescribes.

I had the very question about the ambiguity you removed here - so I follow and agree with your reasoning, audiodude. (Although all prior votes being invalid is troubling)

but the emojis are also charming, so I suppose it will have to be custom both to indicate explicit +1 and also to use :+1: or :-1: if you like the emojis.

By the way, what prevents loose +1 and -1 (like in this very post) from being votes, and what happens if both are present? Does it have to be a +1 or -1 by itself (and not both)?

**Comment by bigjust** [comment]
No, I agree with the only emojis bit. Their fucking charming, and consistency will make it easier to count votes while scanning a thread. Its a little thing, and I suggest reading carefully, but come one, you know thats what we're all going to be doing. Except for @datagrok who I know for a fact has probably built visualizations and a dashboard of sorts that tracks this git repo, and vote counting would have no doubt been the first feature he added.

Ok, that was conjecture. but the point stands. and I know he's thought about it. I know this because I'm staring at a properly licensed, yet empty git repo.

EDIT: I read it now that as long as the comment contains the proper emoji, it wouldn't matter what else was contained in that comment.

**Comment by datagrok** [comment]
Suggestions for other improvements to 311 to pile into this change:

- Change the `Pull Requests must perform exactly one` language so that we might follow-up a vote with an additional commit to a PR that changes the player's score before merging, so that we don't have to do in its own follow-up PR.
- Allow the modification of multiple rule files at once, for a related change (e.g. when updating rules to refer to another's new number). Maybe only if a majority agrees, but we vote on every change anyway...
- make "what has been committed to master" officially the state of the game: `serve as a representation` -> `serve as the canonical representation`
- make it legal to perform other updates while transmuting a rule, like updating the title to conform to ACRONYM

Regardless I intend to :+1: this when voting begins.

---

@bigjust I am delighted that my charade of competency persists uncompromised. Even if it were true, my laziness & poor time management will have prevented me from implementing any such thing. I haven't even got around to updating my score from my last turn. (oops)

Though I am excited about the aforementioned [empty repo](https://github.com/datagrok/automatonomic) which will hopefully eventually hold a nomic game that one plays by submitting patches to the software that verifies incoming patches to itself conform to the rules! :sunglasses:

**Comment by bigjust** [comment]
@datagrok, perhaps https://github.com/chaosbot/chaos will inspire some good ideas/mechanics/etc.

I feel like voting should have started: :+1:

**Comment by datagrok** [comment]
:+1:

**Comment by piersb** [comment]
That time already, huh?

👍

**Comment by selfsame** [comment]
voting :-1: for the dissent points

**Comment by bigjust** [comment]
Unfortunately voting closed at 12:49am this morning

**Comment by bigjust** [comment]
Proposal passes 3-0

**Pull request merged**
