### PR TITLE
314 Virtue Of Written English Letters

### PR DESCRIPTION
**Pull request by selfsame**

### CODE REVIEW

**Comment by selfsame** [comment]
pinging @audiodude @fonorobert @piersb @Cardboard @william42 @kgrover @datagrok @sashahart

**Comment by william42** [comment]
You're banning y?

**Comment by piersb** [comment]
😆 

Seems clear. I'm ready to vote on this.

**Comment by bigjust** [comment]
discourse in general, finally

**Comment by fonorobert** [comment]
I have ambivalent feelings about this. On one hand it's clear that it's awesome, on the other hand it might slow down general discussion.
I'd be glad to hear what others think 🙂

**Comment by fonorobert** [comment]
also, just in case this does pass:

yyyyyyyyyyyyyyyyyyyyyyyYYYyyYYYyYYyYyyy

There, I got it out of my system.

**Comment by datagrok** [comment]
I would like for this rule to provide some clarification as to what is considered "use" of the penultimate letter:

- When a rule is transmuted, is the player who performs that transmutation held liable for uses of the forbidden letter in the text or title of the transmuted rule? (They are not permitted to modify such text at the same time as transmutation.)
- Is the forbidden letter forbidden from the names of players?
- When amending the rule, is the player performing the amending held liable for uses of the forbidden letter in the rule on lines they did not modify? In words their amendment did not add?
- Is a substitute symbol that is not the forbidden letter, but is obviously intended to represent the forbidden letter, also forbidden? Would I be penalized for stating: "This is the alphabet: abcdefghijklmnopqrstuvwx:upside_down_face:z"
- Would emoji whose names contain the forbidden letter trigger the rule, like "hankey" (:hankey:)?

Also it's -> its

---

Aside: I think it is interesting that out of all of our rules, this may be only the second to declare not just that something is forbidden, but also what action should be taken when someone violates the rule.

As someone who may have violated rules in the past, I have been wondering what to do with the feeling of "well, I broke the rule, so now what?" If a rule is not physically impossible to break, but has neither penalty nor means to rewind the game state to before its violation, in what sense is it a rule?

**Comment by bigjust** [comment]
> pinging @audiodude @fonorobert @piersb @Cardboard @william42 @kgrover @datagrok @sashahart

is someone trying to circumvent me?

> When amending the rule, is the player performing the amending held liable for uses of the forbidden letter in the rule on lines they did not modify? In words their amendment did not add?

This is going to be a recurring question, we should come up with a solution via judgement or an amendment. I'll accept pms from anyone who want to conspire on such a thing

> Is a substitute symbol that is not the forbidden letter, but is obviously intended to represent the forbidden letter, also forbidden? Would I be penalized for stating: "This is the alphabet: abcdefghijklmnopqrstuvwx🙃z"

You're adorable

> As someone who may have violated rules in the past, I have been wondering what to do with the feeling of "well, I broke the rule, so now what?" If a rule is not physically impossible to break, but has neither penalty nor means to rewind the game state to before its violation, in what sense is it a rule?

I feel like broken rules only matter if they are called out. Maybe rules can be written to say that violation results in a reversion commit. Also, violations that result in reversions need to be called out before the next successful commit (or turn, or whatever), or then we'll need to have a rebase discussion for affected commits. Or maybe we only do that in the event of conflicts. This is starting to feel like a rabbit hole.

**Comment by audiodude** [comment]
> As someone who may have violated rules in the past, I have been wondering what to do with the feeling of "well, I broke the rule, so now what?" If a rule is not physically impossible to break, but has neither penalty nor means to rewind the game state to before its violation, in what sense is it a rule?

This. I think that a rule that more generally proscribes what to do in the case of broken or violated rules would be more useful than simply making discourse more difficult.

**Comment by datagrok** [comment]
> a rule that more generally proscribes what to do in the case of broken or violated rules would be more useful than simply making discourse more difficult.

I do agree with this, however, usefulness is not necessarily my goal for approving a rule. A silly rule makes the game fun and challenging even if the existing gameplay rules languish in disrepair.

---

We have already seen that referring to existing rules by their number can lead to trouble, since their number changes whenever they are amended. It's safer to refer to them by title or acronym.

If this rule passes, we will no longer be able to refer to the following rules by their title (without incurring a points penalty):

- 101 Abide by all the rules
- 102 Mutability
- 107 Temporality
- 118 Players and joining the game
- 207 Votes per player
- 208 Winner by points
- 210 Conspiracy to rule change
- 307 Temporal Initiated Motion Every Rule (TIMER)
- 309 Bribe Relentlessly, I'm Bribing Everyone (BRIBE)
- 313 Github repository

And we will no longer be able to refer to the following rules by their title _or their acronym_:

- 302 All Created Rule Orders Now Yield Monikers (ACRONYM)

This is to say, I'm eager to see this rule in play to see how we manage to cope with it.

I'd still like to see the changes I requested earlier though.

**Comment by sashahart** [comment]
I can't vote for this due to a disagreeable ambiguity in the phrase "the english alphabet" - who is to say what is in that alphabet, and in which order?

**Comment by selfsame** [comment]
@sashahart https://en.wikipedia.org/wiki/English_alphabet
q7693eb

**Comment by selfsame** [comment]
Voting is now open, please take another look at the proposal as it's been updated based on some suggestions from @datagrok

**Comment by piersb** [comment]
👍 

yyyyYYyYYYyYyYYyyYYYyyYYY

**Comment by datagrok** [comment]
👍 ƛƔɏɎȳȲƴƳλΫγϒϓϔҮүҰұӋӌУӳӮӯӰӱӲץႬႸჄሃᎩᏗᏱᥡ᨟ᨂᵞᵧỾỿỲỹỸỷỶỵỴỳẏẎῨῩῪΎ⑂ⓨ⒴⤙⤚ⲨⲩⲖⲗⴘⵖ𝈘𝈛𝐲𝑌𝐘𝑦𝒀𝒴𝒚𝓨𝔂𝔜𝔶𝕐𝕪𝖞𝖄𝗒𝘆𝘠𝘺𝙮𝙔𝚈𝚢𝛌𝛄𝛾𝜓𝝀𝝍𝝭𝝺𝞧

**Comment by audiodude** [comment]
I vote no :-1: 

Maybe I'll get some dissent points for when I violate this rule.

**Comment by william42** [comment]
Well, I can't say yes to this because "yes" contains the twenty-fifth letter, so I have to say no :-1:

**Comment by fonorobert** [comment]
i vote in the affirmative 👍

**Comment by bigjust** [comment]
👍

**Comment by bigjust** [comment]
Proposal passes 4-2, hope everyone got all of the 'y's out of their system.

EDIT: a word

**Comment by fonorobert** [comment]
As per 205(Moment of completion) this new rule took effect at the completion of voting. As per this new rule @bigjust is in violation with their latest comment.

**Comment by datagrok** [comment]
Assuming @selfsame's turn ended at [the time the merge was performed](https://github.com/audiodude/tiny-nomic/pull/42#event-1127987353), 125.3 hours have elapsed, or 2.6 48-hour periods, meaning FAST has forfeited @fonorobert and @piersb's turns and now @Cardboard has 18.7 hours remaining to submit a rule before their turn is also forfeit and @william42's turn will begin.

**Pull request merged**
