### PR TITLE
New rule: 301 - Contents of player file

### PR DESCRIPTION
**Pull request by audiodude**
Since there are currently no restrictions on player files except that they contain the current score of the player (and their naming format), I've decided that some order might be in order.

### CODE REVIEW

**Comment by piersb** [comment]
I quite like the idea of putting more happyfuntime into our player files rather than less. So I vote against.

👎

**Comment by fonorobert** [comment]
I like the idea of having some basic structure in the player files, I don't think this would be too much. I vote for :+1:

**Comment by Cardboard** [comment]
I'm interested in seeing where this could go :+1:

**Comment by selfsame** [comment]
proposing removal of the section regarding newlines :-1:

**Comment by kgrover** [comment]
proposing removal of the line limit 👎

**Comment by audiodude** [comment]
Okay, I see 4 players voting, so the voting is complete. #6 fails and I have -10 points. @selfsame it is your turn.

**Pull request closed without merging**
