### PR TITLE
Add Rule 315: GAME OVER.

### PR DESCRIPTION
**Pull request by audiodude**
To deal with the current rash of turn forfeitures, I propose the following rule. I hope all find it to be swift and merciless.

### CODE REVIEW

**Comment by datagrok** [comment]
@audiodude, is the motivation behind this rule to encourage plakers to be more diligent about taking their turns on schedule, lest them feel v. bad because them cause the game to end? Or are there other motivations (hast thou perhaps lost interest in hosting the game?) I think knowing this might influence how I vote.

**Comment by audiodude** [comment]
It's the former. I wish there to be some grievous consequence for skipping turns. At first, I was thinking of a rule that caused players to forfeit the game if two consecutive turns were skipped. But then I thought it might be better to have some group motivation to keep things going.

**Comment by fonorobert** [comment]
This seems a little harsh, although harsh might be just what we need to liven up the game and introduce some real risk. Not sure so far where I stand on this, would be interested to hear what others think.

**Comment by piersb** [comment]
What about Geneva Convention? Did she die in vain?

https://ihl-databases.icrc.org/ihl/WebART/380-600038

**Comment by selfsame** [comment]
T.I.M.E.R does state that skipping ones turn results in a loss of ten points, though we seem to be rather bad at enforcing penalties around here

**Comment by bigjust** [comment]
I'd be more amenable to threatening expulsion of a single person due to two consecutive skips... that might be me next proposal

**Comment by selfsame** [comment]
@audiodude has used the forbidden letter fifteen times in this PR and once in a comment, i regret that I must deduct 32 points from their score.

**Comment by piersb** [comment]
I thought the forbidden letter was a two-point deduction per message, not per use? Did I misread?

**Comment by piersb** [comment]
Ah, it's per offense.

So it depends on whether one reads each letter as a single offense, or each missive as a single offense.

**Comment by datagrok** [comment]
🤔 I suspect the immediate consequence of this rule will be that someone who neither reads GitHub's deluge of notification-spam nor visits the GitHub site dail█ will suddenl█ remember the█ haven't checked on the game in a bit too long and the█'ll show up to find that 1. ever█one is mad at them and 2. nothing can be done about it because the game is over. That doesn't feel fun to me, so if left in its current state, I'm sure I'll vote against this proposal.

I think that rather than tr█ to enact harsher punishments to elicit compliance, we should reexamine the underl█ing game mechanic that people are having trouble with. I feel like I'm prett█ enthusiastic about the game and even I forfeited m█ recent turn.

In video games there is a much-panned mechanic called [quick time events](https://en.wikipedia.org/wiki/Quick_time_event). I feel like the well-intentioned _FAST_ has an unintended consequence of making our Nomic game analogous to these. We have to pa█ close attention to the time at which a PR is closed, then wait without notification to quickl█ perform our turn actions at the appropriate time. Our actions must occur in s█nchron█ with the time windows defined b█ _TIMER_, and the windows are not fixed; the█ shift ever█ time someone begins their turn.

I'd like to turn this into more of a turn-based-strateg█ like XCOM, where we ma█ all prepare our moves concurrentl█/as█nchronousl█, allowing the round to progress quickl█ after all pla█ers have, at their convenience, locked in their pla█.

I haven't figured out how to word it █et, or how to get appropriate parts of both _FAST_ and _TIMER_ overridden appropriatel█, but this is what I have in mind (if the game does not end before m█ next turn 😉):

- Rule modification PRs ma█ be created not just at the beginning of that pla█er's turn, but at an█ time b█ an█ pla█er, and ma█ be updated at an█ time.
- A pla█er ma█ vote at an█ time, but since PRs ma█ change the█ must mention the commit hash that the█ are voting on.
- Remove all restrictions on who ma█ merge an approved PR (rel█ on penalties for incorrect merges)
- In this wa█, when a pla█er's "turn" begins, their lowest-numbered active PR could in theor█ be instantaneousl█ merged and allow the game to continue quickl█.

We would still be rel█ing on the time windows FAST defines to allow time for pla█ers who want to vote or submit a PR to do so, but b█ allowing voting, rule proposal, and discussion to happen more as█nchronousl█ I think more pla█ers would be able to participate whenever the█ find time to do so, and in man█ cases the█ would need not even be present for a successful PR merge.

**Comment by audiodude** [comment]
I really like where you're going with this @datagrok and largely agree with you. Especially in terms of what is likely to happen: someone ignores the game for a little while and comes back to find it in flames. Not a great experience.

I would say that perhaps what we really want is to modify TIMER/FAST so that the other players can vote to forfeit someone's turn once 48 hours have elapsed. And it might not have to be a unanimous or even majority vote. Like in my rule proposal, perhaps it's a vote of 1/3 of the players or something. That way we still have deadlines, but they're only enforced if everyone else is actively paying attention and wants to enforce them.

**Comment by selfsame** [comment]
@audiodude has invoked the forbidden vowel 19 times and will now be penalized 38 points

**Comment by fonorobert** [comment]
I think we are in the voting period on this one. While I agree with the intent behind the proposal, I now also think that this might be too harsh, so I vote nay :-1:

**Comment by william42** [comment]
I'm going to vote no because deleting the repo seems too harsh 👎

**Comment by bigjust** [comment]
:-1:

**Comment by piersb** [comment]
NOS!

👎

**Comment by selfsame** [comment]
voting :-1:

also @fonorobert has used that letter one time and will be penalized 2 points

**Comment by datagrok** [comment]
Fffffffuuuuuuuuuuuu I missed the voting period!

According to _FAST_,

> (1.b) In the case of a turn whose proposal is unsuccessful, the turn ends and the next turn subsequentl_ begins when the vote concludes, either through all players having voted or the timer in TIMER (1.e) elapsing.

So audiodude's turn ended Jul 05, 04:36PM and @selfsame must begin their turn before Jul 07, 04:36PM. (1d + 19h from now).

Note: my script has a bug and will calculate this wrong after this PR is closed. I mistakenlx made it interpret the time the PR is closed as the time that the turn ended.

Am I allowed to close this PR? I don't remember. IOLO doing it anniewaze

**Pull request closed without merging**
